---
abstract: 'Select from the available application views by type'
author:
  - 'Tomas Doran (t0m), C<< <bobtfish@bobtfish.net> >>'
build_requires:
  Catalyst::Action::Renderview: 0
  Catalyst::Controller::ActionRole: 0
  Catalyst::Runtime: 5.80
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-ActionRole-FindViewByIsa
no_index:
  directory:
    - inc
    - t
resources:
  license: http://dev.perl.org/licenses/
version: 0.000001
